### ISSUE TITLE
Some parts of the AK weapons (apart from the saiga 12 and RD-704) disappears if shot without a suppressor on some pms 

### ISSUE THREAD

**Issue by R1stie** [dar-su/arc9_eft_ak#5]
For some reason if you use a non humanoid player model (example being a furry pm, idfk) it causes some of the weapon's parts to bug out and go transparent for a split second when shot. I would've thought the issue was the player model  but after testing with the suppressor it was magically fixed on every player model. I suspect that it perhaps have something to do with the muzzle flashes of the aks since this issue doesn't apply to other weapons as well but that's my best guess. Hopefully this issue can be addressed. 

I provided a video on streamable to possibly help fix this.
https://streamable.com/jk3fhb

**Comment by Wgairborne** [comment]
this dude def using a furry pm

**Comment by R1stie** [comment]
> this dude def using a furry pm

Never said I wasn't? I used a furry player model in my example video if you even watched that, but even non furry player models that normally worked with darcu's guns doesn't work with the guns for some odd reason.
 :/

**Comment by dar-su** [comment]
Can you drop link to that model
Btw try ak74 and mp5 from arc9 fas2 pack

**Comment by R1stie** [comment]
> Can you drop link to that model Btw try ak74 and mp5 from arc9 fas2 pack

Here's the player model I was using in the video, more specifically the yellow protogen (but the issue happens on both of them).
https://steamcommunity.com/sharedfiles/filedetails/?id=2038216533

And I tested the 2 guns from the FAS2 pack and got nothing wrong with them, at least not the same error as the aks as shown in this video. **BUT did find something**! When you shoot the gun and look downwards your C_hands and the parts of the gun that go invisible for a split second appear there at the same time they they disappear, so it seems that they're just being moved downwards. Hopefully that information helps
Video showing what I mean: https://streamable.com/j0fier

**Comment by dar-su** [comment]
No idea
Probably some source engine things or/and bad c_hands setup
Solution - do not use those models, their hands looks really ugly anyway
